apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ipps
spec:
  selector:
    project: ftps-pod-proj
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: p2
      port: 21
      targetPort: 21
    - protocol: TCP
      name: p1
      port: 20000
      targetPort: 20000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps-deploy
spec:
  selector:
    matchLabels:
      project: ftps-pod-proj
  template:
    metadata:
      labels:
        project: ftps-pod-proj
    spec:
      containers:
      - name: ftps-pod
        image: ftps
        imagePullPolicy: Never
        ports:
        - name: p1
          containerPort: 21
        - name: p2
          containerPort: 20000
                
